import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer | Lumina Constellation',
  description:
    'Important legal disclaimer for Lumina Constellation. All spiritual, astrological, tarot, dream, and memorial content is for entertainment purposes only and is not medical, psychological, legal, or financial advice.',
};

export default function Page() {
  return (
    <div className="min-h-screen bg-mystic-gradient text-purple-100">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <a
          href="/"
          className="text-amber-300 text-sm hover:underline mb-6 inline-block"
        >
          ← Back to Home
        </a>
        <h1
          className="text-3xl font-bold text-gold mb-2"
          style={{ fontFamily: 'var(--font-cormorant), serif' }}
        >
          Disclaimer
        </h1>
        <p className="text-xs text-purple-100/50 mb-8">
          Please read carefully · Applies to all Lumina Constellation products
        </p>

        {/* Critical notice banner */}
        <div className="glass-card rounded-xl p-5 mb-8 border border-amber-300/40">
          <p className="text-sm font-semibold text-amber-300 mb-1">
            ⚠ Important Notice
          </p>
          <p className="text-sm text-purple-100/90">
            All spiritual, astrological, tarot, numerology, dream
            interpretation, and memorial content generated by Lumina
            Constellation is provided{' '}
            <strong className="text-amber-200">
              for entertainment purposes only
            </strong>
            . It is <strong>not</strong> a substitute for professional medical,
            psychological, legal, or financial advice.
          </p>
        </div>

        <div className="space-y-6 text-sm leading-relaxed text-purple-100/80">
          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              1. Entertainment Purposes Only
            </h2>
            <p>
              The readings, reports, and creative narratives produced by our AI
              Spiritual Companion (Vega), Genealogy (Cassiopeia), and related
              products are works of generative content intended for reflection,
              inspiration, and entertainment. They are not predictions of future
              events, and Lumina Constellation makes no claim as to their
              factual accuracy, scientific validity, or supernatural origin.
              Astrology, tarot, numerology, Bazi, and dream interpretation are
              symbolic frameworks and are not recognized as empirical sciences.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              2. Not Medical, Psychological, Legal, or Financial Advice
            </h2>
            <p>
              Nothing provided by Lumina Constellation constitutes medical,
              psychological, legal, or financial advice, diagnosis, or
              treatment recommendation. Our content must never be used as a
              basis for decisions about your health, mental wellbeing,
              relationships, career, investments, or legal matters. Always
              consult a qualified, licensed professional — such as a physician,
              therapist, attorney, or financial advisor — for guidance in these
              areas. Never disregard or delay seeking professional advice
              because of something you read in our products.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              3. Caregiver Support — Not a Medical Diagnosis
            </h2>
            <p>
              The Lyra Caregiver Support product offers organizational tools,
              reminders, reflective prompts, and educational resources for
              people caring for loved ones. Lyra does <strong>not</strong>{' '}
              provide medical diagnoses, treatment plans, or clinical advice,
              and it is not a substitute for care from physicians, nurses,
              hospice teams, or other healthcare professionals. Symptoms,
              medication changes, emergencies, or any concern about a care
              recipient’s condition must be discussed with a qualified
              healthcare provider. In a medical emergency, contact your local
              emergency services immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              4. Digital Memorial — Creative Tribute, Not Channeling
            </h2>
            <p>
              The Pleiades Digital Memorial product creates narrative tributes,
              memory keepsakes, and reflective letters inspired by the
              information you provide about a person who has passed. These
              outputs are works of creative writing and are intended to support
              remembrance and emotional processing. They are{' '}
              <strong>not</strong> literal channeling, communication with the
              deceased, or claims about an afterlife. Any resemblance to actual
              statements by the departed is coincidental and the result of
              generative modeling based on your inputs. If you are experiencing
              grief that feels overwhelming, please consider reaching out to a
              grief counselor or mental health professional.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              5. AI-Generated Content May Be Inaccurate
            </h2>
            <p>
              All products in the Lumina Constellation use large language models
              that can produce plausible-sounding but incorrect, incomplete, or
              biased outputs (sometimes called “hallucinations”). You are
              responsible for evaluating the accuracy and appropriateness of any
              content before relying on, sharing, or acting on it. Lumina
              Constellation does not warrant that outputs will be factually
              correct, culturally appropriate, or suitable for any particular
              purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              6. Seek Professional Help When Needed
            </h2>
            <p>
              If you are experiencing a crisis — including thoughts of
              self-harm, suicidal ideation, abuse, addiction, or any other
              emergency — please seek immediate help from qualified
              professionals or emergency services in your region. Lumina
              Constellation products are not crisis resources and should not be
              used in place of professional intervention.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              7. No Guarantees of Outcomes
            </h2>
            <p>
              Lumina Constellation does not guarantee any specific outcome from
              using its products, including improvements in mood, relationships,
              finances, or life events. Testimonials and feature descriptions
              illustrate possibilities and do not represent typical or promised
              results.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              8. Acceptance
            </h2>
            <p>
              By using any Lumina Constellation product, you acknowledge that
              you have read, understood, and accepted this Disclaimer, and that
              you use the Services at your own discretion and risk. If you do
              not agree, please discontinue use.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gold mb-2">
              9. Contact
            </h2>
            <p>
              Questions about this Disclaimer? Email{' '}
              <a
                href="mailto:support@lumina.constellation"
                className="text-amber-300 hover:underline"
              >
                support@lumina.constellation
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
